#!/usr/bin/env zsh

# rerun: build target and run it with args

local target="${1:?}"
shift

function resolve_most_git_superproject()
{
  local found_dir="$(git rev-parse --show-toplevel)"

  while true; do
    local super="$(git -C "$found_dir" rev-parse --show-superproject-working-tree)"
    if [[ -z "$super" ]]; then
      break
    fi

    found_dir="$super"
  done
  echo "$found_dir"
}

function configure_cmake()
{
  : ${1:?}
  mkdir -p "${1}";
  "${CMAKE}" \
    -S \
    . \
    -B \
    "${1}" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON;

  echo "Build done...";
  sleep 5;
}

clear

super="$(resolve_most_git_superproject)"
cd "$super"

executable=""

if [[ -e "CMakeLists.txt" ]]; then
  : "${CMAKE:?}"
  local build_dir="./build_x64"
  local config="Debug"

  [[ -d "${build_dir}" ]] || configure_cmake "${build_dir}";
  "${CMAKE}" --build "${build_dir}" --config "${config}" --target "${target}"
  (( ! $? )) || return

  executable="$(find ${build_dir}/${target}/${config} -iname '*.exe')"
elif [[ -e "fbuild.bff" ]]; then
  : "${FBUILD:?}"

  "${FBUILD}" -dist -cache "${target}"
  (( ! $? )) || return

  executable_name="${target%-*-*-*-*}"
  executable="`pwd`/${target/#${executable_name}-/}/${executable_name}"
fi

if ! command -v ${executable} 2>&1 >/dev/null;
then
	executable="${executable}.exe"
fi

"${executable}" ${*}
