#!/usr/bin/env zsh

# rerun: build target and run it with args

: "${FBUILD:?}"
local target=${1:?}
shift

clear

${FBUILD} -dist -cache "${target}"
(( ! $? )) || return

local executable_name="${target%-*-*-*-*}"
local executable="`pwd`/${target/#${executable_name}-/}/${executable_name}"

if ! command -v ${executable} 2>&1 >/dev/null;
then
	executable="${executable}.exe"
fi

"${executable}" "${*}"
